@extends('layouts.app')

@section('content')

<div class="card-body justify-content">
                        <div style="text-align: justify; color: black; padding:1.25rem;" >

                            <h2 style='margin-right:0cm;margin-left:0cm;font-size:24px;font-family:"Times New Roman",serif;font-weight:bold;margin-top:0cm;margin-bottom:13.5pt;background:white;'><strong><span style='font-size:15px;font-family:"Calibri",sans-serif;color:black;font-weight:normal;'>Terms and Conditions</span></strong></h2>
                            <p style='margin-right:0cm;margin-left:0cm;font-size:15px;font-family:"Calibri",sans-serif;margin-top:0cm;margin-bottom:15.0pt;line-height:107%;background:white;'><span style='font-size:15px;font-family:"Calibri",sans-serif;color:black;'>Welcome to COS KMS !</span></p>
                            <p style='margin-right:0cm;margin-left:0cm;font-size:15px;font-family:"Calibri",sans-serif;margin-top:0cm;margin-bottom:15.0pt;line-height:107%;background:white;'><span style='font-size:15px;font-family:"Calibri",sans-serif;color:black;'>These terms and conditions outline the rules and regulations for the use of Technological University of the Philippines Manila - College of Science &apos;s Website, located at www.coskms.edu.</span></p>
                            <p style='margin-right:0cm;margin-left:0cm;font-size:15px;font-family:"Calibri",sans-serif;margin-top:0cm;margin-bottom:15.0pt;line-height:107%;background:white;'><span style='font-size:15px;font-family:"Calibri",sans-serif;color:black;'>By accessing this website we assume you accept these terms and conditions. Do not continue to use COS KMS if you do not agree to take all of the terms and conditions stated on this page.</span></p>
                            <p style='margin-right:0cm;margin-left:0cm;font-size:15px;font-family:"Calibri",sans-serif;margin-top:0cm;margin-bottom:15.0pt;line-height:107%;background:white;'><span style='font-size:15px;font-family:"Calibri",sans-serif;color:black;'>The following terminology applies to these Terms and Conditions, Privacy Statement and Disclaimer Notice and all Agreements: &quot;Client&quot;, &quot;You&quot; and &quot;Your&quot; refers to you, the person log on this website and compliant to the Company&rsquo;s terms and conditions. &quot;The Company&quot;, &quot;Ourselves&quot;, &quot;We&quot;, &quot;Our&quot; and &quot;Us&quot;, refers to our Company. &quot;Party&quot;, &quot;Parties&quot;, or &quot;Us&quot;, refers to both the Client and ourselves. All terms refer to the offer, acceptance and consideration of payment necessary to undertake the process of our assistance to the Client in the most appropriate manner for the express purpose of meeting the Client&rsquo;s needs in respect of provision of the Company&rsquo;s stated services, in accordance with and subject to, prevailing law of Netherlands. Any use of the above terminology or other words in the singular, plural, capitalization and/or he/she or they, are taken as interchangeable and therefore as referring to same.</span></p>
                            <h3 style='margin-top:0cm;margin-right:0cm;margin-bottom:13.5pt;margin-left:0cm;line-height:107%;font-size:16px;font-family:"Calibri Light",sans-serif;color:#1F3763;font-weight:normal;background:white;'><strong><span style='font-size:15px;line-height:107%;font-family:"Calibri",sans-serif;color:black;'>Cookies</span></strong></h3>
                            <p style='margin-right:0cm;margin-left:0cm;font-size:15px;font-family:"Calibri",sans-serif;margin-top:0cm;margin-bottom:15.0pt;line-height:107%;background:white;'><span style='font-size:15px;font-family:"Calibri",sans-serif;color:black;'>We employ the use of cookies. By accessing COS KMS , you agreed to use cookies in agreement with the Technological University of the Philippines Manila - College of Science &apos;s Privacy Policy.</span></p>
                            <p style='margin-right:0cm;margin-left:0cm;font-size:15px;font-family:"Calibri",sans-serif;margin-top:0cm;margin-bottom:15.0pt;line-height:107%;background:white;'><span style='font-size:15px;font-family:"Calibri",sans-serif;color:black;'>Most interactive websites use cookies to let us retrieve the user&rsquo;s details for each visit. Cookies are used by our website to enable the functionality of certain areas to make it easier for people visiting our website. Some of our affiliate/advertising partners may also use cookies.</span></p>
                            <h3 style='margin-top:0cm;margin-right:0cm;margin-bottom:13.5pt;margin-left:0cm;line-height:107%;font-size:16px;font-family:"Calibri Light",sans-serif;color:#1F3763;font-weight:normal;background:white;'><strong><span style='font-size:15px;line-height:107%;font-family:"Calibri",sans-serif;color:black;'>License</span></strong></h3>
                            <p style='margin-right:0cm;margin-left:0cm;font-size:15px;font-family:"Calibri",sans-serif;margin-top:0cm;margin-bottom:15.0pt;line-height:107%;background:white;'><span style='font-size:15px;font-family:"Calibri",sans-serif;color:black;'>Unless otherwise stated, Technological University of the Philippines Manila - College of Science and/or its licensors own the intellectual property rights for all material on COS KMS . All intellectual property rights are reserved. You may access this from COS KMS for your own personal use subjected to restrictions set in these terms and conditions.</span></p>
                            <p style='margin-right:0cm;margin-left:0cm;font-size:15px;font-family:"Calibri",sans-serif;margin-top:0cm;margin-bottom:15.0pt;line-height:107%;background:white;'><span style='font-size:15px;font-family:"Calibri",sans-serif;color:black;'>You must not:</span></p>
                            <ul style="margin-bottom:0cm;" type="disc">
                                <li style='margin-top:0cm;margin-right:0cm;margin-bottom:8.0pt;margin-left:0cm;line-height:normal;font-size:15px;font-family:"Calibri",sans-serif;background:white;'><span style="color:black;">Republish material from COS KMS</span></li>
                                <li style='margin-top:0cm;margin-right:0cm;margin-bottom:8.0pt;margin-left:0cm;line-height:normal;font-size:15px;font-family:"Calibri",sans-serif;background:white;'><span style="color:black;">Sell, rent or sub-license material from COS KMS</span></li>
                                <li style='margin-top:0cm;margin-right:0cm;margin-bottom:8.0pt;margin-left:0cm;line-height:normal;font-size:15px;font-family:"Calibri",sans-serif;background:white;'><span style="color:black;">Reproduce, duplicate or copy material from COS KMS</span></li>
                                <li style='margin-top:0cm;margin-right:0cm;margin-bottom:8.0pt;margin-left:0cm;line-height:normal;font-size:15px;font-family:"Calibri",sans-serif;background:white;'><span style="color:black;">Redistribute content from COS KMS</span></li>
                            </ul>
                            <p style='margin-right:0cm;margin-left:0cm;font-size:15px;font-family:"Calibri",sans-serif;margin-top:0cm;margin-bottom:15.0pt;line-height:107%;background:white;'><span style='font-size:15px;font-family:"Calibri",sans-serif;color:black;'>This Agreement shall begin on the date hereof. Our Terms and Conditions were created with the help of the&nbsp;</span><span style="color:black;"><a href="https://www.termsfeed.com/terms-conditions-generator/"><span style='font-size:15px;font-family:"Calibri",sans-serif;color:black;'>Terms And Conditions Generator</span></a></span><span style='font-size:15px;font-family:"Calibri",sans-serif;color:black;'>.</span></p>
                            <p style='margin-right:0cm;margin-left:0cm;font-size:15px;font-family:"Calibri",sans-serif;margin-top:0cm;margin-bottom:15.0pt;line-height:107%;background:white;'><span style='font-size:15px;font-family:"Calibri",sans-serif;color:black;'>Parts of this website offer an opportunity for users to post and exchange opinions and information in certain areas of the website. Technological University of the Philippines Manila - College of Science does not filter, edit, publish or review Comments prior to their presence on the website. Comments do not reflect the views and opinions of Technological University of the Philippines Manila - College of Science ,its agents and/or affiliates. Comments reflect the views and opinions of the person who post their views and opinions. To the extent permitted by applicable laws, Technological University of the Philippines Manila - College of Science shall not be liable for the Comments or for any liability, damages or expenses caused and/or suffered as a result of any use of and/or posting of and/or appearance of the Comments on this website.</span></p>
                            <p style='margin-right:0cm;margin-left:0cm;font-size:15px;font-family:"Calibri",sans-serif;margin-top:0cm;margin-bottom:15.0pt;line-height:107%;background:white;'><span style='font-size:15px;font-family:"Calibri",sans-serif;color:black;'>Technological University of the Philippines Manila - College of Science reserves the right to monitor all Comments and to remove any Comments which can be considered inappropriate, offensive or causes breach of these Terms and Conditions.</span></p>
                            <p style='margin-right:0cm;margin-left:0cm;font-size:15px;font-family:"Calibri",sans-serif;margin-top:0cm;margin-bottom:15.0pt;line-height:107%;background:white;'><span style='font-size:15px;font-family:"Calibri",sans-serif;color:black;'>You warrant and represent that:</span></p>
                            <ul style="margin-bottom:0cm;" type="disc">
                                <li style='margin-top:0cm;margin-right:0cm;margin-bottom:8.0pt;margin-left:0cm;line-height:normal;font-size:15px;font-family:"Calibri",sans-serif;background:white;'><span style="color:black;">You are entitled to post the Comments on our website and have all necessary licenses and consents to do so;</span></li>
                                <li style='margin-top:0cm;margin-right:0cm;margin-bottom:8.0pt;margin-left:0cm;line-height:normal;font-size:15px;font-family:"Calibri",sans-serif;background:white;'><span style="color:black;">The Comments do not invade any intellectual property right, including without limitation copyright, patent or trademark of any third party;</span></li>
                                <li style='margin-top:0cm;margin-right:0cm;margin-bottom:8.0pt;margin-left:0cm;line-height:normal;font-size:15px;font-family:"Calibri",sans-serif;background:white;'><span style="color:black;">The Comments do not contain any defamatory, libelous, offensive, indecent or otherwise unlawful material which is an invasion of privacy</span></li>
                                <li style='margin-top:0cm;margin-right:0cm;margin-bottom:8.0pt;margin-left:0cm;line-height:normal;font-size:15px;font-family:"Calibri",sans-serif;background:white;'><span style="color:black;">The Comments will not be used to solicit or promote business or custom or present commercial activities or unlawful activity.</span></li>
                            </ul>
                            <p style='margin-right:0cm;margin-left:0cm;font-size:15px;font-family:"Calibri",sans-serif;margin-top:0cm;margin-bottom:15.0pt;line-height:107%;background:white;'><span style='font-size:15px;font-family:"Calibri",sans-serif;color:black;'>You hereby grant Technological University of the Philippines Manila - College of Science a non-exclusive license to use, reproduce, edit and authorize others to use, reproduce and edit any of your Comments in any and all forms, formats or media.</span></p>
                            <h3 style='margin-top:0cm;margin-right:0cm;margin-bottom:13.5pt;margin-left:0cm;line-height:107%;font-size:16px;font-family:"Calibri Light",sans-serif;color:#1F3763;font-weight:normal;background:white;'><strong><span style='font-size:15px;line-height:107%;font-family:"Calibri",sans-serif;color:black;'>Hyperlinking to our Content</span></strong></h3>
                            <p style='margin-right:0cm;margin-left:0cm;font-size:15px;font-family:"Calibri",sans-serif;margin-top:0cm;margin-bottom:15.0pt;line-height:107%;background:white;'><span style='font-size:15px;font-family:"Calibri",sans-serif;color:black;'>The following organizations may link to our Website without prior written approval:</span></p>
                            <ul style="margin-bottom:0cm;" type="disc">
                                <li style='margin-top:0cm;margin-right:0cm;margin-bottom:8.0pt;margin-left:0cm;line-height:normal;font-size:15px;font-family:"Calibri",sans-serif;background:white;'><span style="color:black;">Government agencies;</span></li>
                                <li style='margin-top:0cm;margin-right:0cm;margin-bottom:8.0pt;margin-left:0cm;line-height:normal;font-size:15px;font-family:"Calibri",sans-serif;background:white;'><span style="color:black;">Search engines;</span></li>
                                <li style='margin-top:0cm;margin-right:0cm;margin-bottom:8.0pt;margin-left:0cm;line-height:normal;font-size:15px;font-family:"Calibri",sans-serif;background:white;'><span style="color:black;">News organizations;</span></li>
                                <li style='margin-top:0cm;margin-right:0cm;margin-bottom:8.0pt;margin-left:0cm;line-height:normal;font-size:15px;font-family:"Calibri",sans-serif;background:white;'><span style="color:black;">Online directory distributors may link to our Website in the same manner as they hyperlink to the Websites of other listed businesses; and</span></li>
                                <li style='margin-top:0cm;margin-right:0cm;margin-bottom:8.0pt;margin-left:0cm;line-height:normal;font-size:15px;font-family:"Calibri",sans-serif;background:white;'><span style="color:black;">System wide Accredited Businesses except soliciting non-profit organizations, charity shopping malls, and charity fundraising groups which may not hyperlink to our Web site.</span></li>
                            </ul>
                            <p style='margin-right:0cm;margin-left:0cm;font-size:15px;font-family:"Calibri",sans-serif;margin-top:0cm;margin-bottom:15.0pt;line-height:107%;background:white;'><span style='font-size:15px;font-family:"Calibri",sans-serif;color:black;'>These organizations may link to our home page, to publications or to other Website information so long as the link: (a) is not in any way deceptive; (b) does not falsely imply sponsorship, endorsement or approval of the linking party and its products and/or services; and (c) fits within the context of the linking party&rsquo;s site.</span></p>
                            <p style='margin-right:0cm;margin-left:0cm;font-size:15px;font-family:"Calibri",sans-serif;margin-top:0cm;margin-bottom:15.0pt;line-height:107%;background:white;'><span style='font-size:15px;font-family:"Calibri",sans-serif;color:black;'>We may consider and approve other link requests from the following types of organizations:</span></p>
                            <ul style="margin-bottom:0cm;" type="disc">
                                <li style='margin-top:0cm;margin-right:0cm;margin-bottom:8.0pt;margin-left:0cm;line-height:normal;font-size:15px;font-family:"Calibri",sans-serif;background:white;'><span style="color:black;">commonly-known consumer and/or business information sources;</span></li>
                                <li style='margin-top:0cm;margin-right:0cm;margin-bottom:8.0pt;margin-left:0cm;line-height:normal;font-size:15px;font-family:"Calibri",sans-serif;background:white;'><span style="color:black;">dot.com community sites;</span></li>
                                <li style='margin-top:0cm;margin-right:0cm;margin-bottom:8.0pt;margin-left:0cm;line-height:normal;font-size:15px;font-family:"Calibri",sans-serif;background:white;'><span style="color:black;">associations or other groups representing charities;</span></li>
                                <li style='margin-top:0cm;margin-right:0cm;margin-bottom:8.0pt;margin-left:0cm;line-height:normal;font-size:15px;font-family:"Calibri",sans-serif;background:white;'><span style="color:black;">online directory distributors;</span></li>
                                <li style='margin-top:0cm;margin-right:0cm;margin-bottom:8.0pt;margin-left:0cm;line-height:normal;font-size:15px;font-family:"Calibri",sans-serif;background:white;'><span style="color:black;">internet portals;</span></li>
                                <li style='margin-top:0cm;margin-right:0cm;margin-bottom:8.0pt;margin-left:0cm;line-height:normal;font-size:15px;font-family:"Calibri",sans-serif;background:white;'><span style="color:black;">accounting, law and consulting firms; and</span></li>
                                <li style='margin-top:0cm;margin-right:0cm;margin-bottom:8.0pt;margin-left:0cm;line-height:normal;font-size:15px;font-family:"Calibri",sans-serif;background:white;'><span style="color:black;">educational institutions and trade associations.</span></li>
                            </ul>
                            <p style='margin-right:0cm;margin-left:0cm;font-size:15px;font-family:"Calibri",sans-serif;margin-top:0cm;margin-bottom:15.0pt;line-height:107%;background:white;'><span style='font-size:15px;font-family:"Calibri",sans-serif;color:black;'>We will approve link requests from these organizations if we decide that: (a) the link would not make us look unfavorably to ourselves or to our accredited businesses; (b) the organization does not have any negative records with us; (c) the benefit to us from the visibility of the hyperlink compensates the absence of Technological University of the Philippines Manila - College of Science ; and (d) the link is in the context of general resource information.</span></p>
                            <p style='margin-right:0cm;margin-left:0cm;font-size:15px;font-family:"Calibri",sans-serif;margin-top:0cm;margin-bottom:15.0pt;line-height:107%;background:white;'><span style='font-size:15px;font-family:"Calibri",sans-serif;color:black;'>These organizations may link to our home page so long as the link: (a) is not in any way deceptive; (b) does not falsely imply sponsorship, endorsement or approval of the linking party and its products or services; and (c) fits within the context of the linking party&rsquo;s site.</span></p>
                            <p style='margin-right:0cm;margin-left:0cm;font-size:15px;font-family:"Calibri",sans-serif;margin-top:0cm;margin-bottom:15.0pt;line-height:107%;background:white;'><span style='font-size:15px;font-family:"Calibri",sans-serif;color:black;'>If you are one of the organizations listed in paragraph 2 above and are interested in linking to our website, you must inform us by sending an e-mail to Technological University of the Philippines Manila - College of Science . Please include your name, your organization name, contact information as well as the URL of your site, a list of any URLs from which you intend to link to our Website, and a list of the URLs on our site to which you would like to link. Wait 2-3 weeks for a response.</span></p>
                            <p style='margin-right:0cm;margin-left:0cm;font-size:15px;font-family:"Calibri",sans-serif;margin-top:0cm;margin-bottom:15.0pt;line-height:107%;background:white;'><span style='font-size:15px;font-family:"Calibri",sans-serif;color:black;'>Approved organizations may hyperlink to our Website as follows:</span></p>
                            <ul style="margin-bottom:0cm;" type="disc">
                                <li style='margin-top:0cm;margin-right:0cm;margin-bottom:8.0pt;margin-left:0cm;line-height:normal;font-size:15px;font-family:"Calibri",sans-serif;background:white;'><span style="color:black;">By use of our corporate name; or</span></li>
                                <li style='margin-top:0cm;margin-right:0cm;margin-bottom:8.0pt;margin-left:0cm;line-height:normal;font-size:15px;font-family:"Calibri",sans-serif;background:white;'><span style="color:black;">By use of the uniform resource locator being linked to; or</span></li>
                                <li style='margin-top:0cm;margin-right:0cm;margin-bottom:8.0pt;margin-left:0cm;line-height:normal;font-size:15px;font-family:"Calibri",sans-serif;background:white;'><span style="color:black;">By use of any other description of our Website being linked to that makes sense within the context and format of content on the linking party&rsquo;s site.</span></li>
                            </ul>
                            <p style='margin-right:0cm;margin-left:0cm;font-size:15px;font-family:"Calibri",sans-serif;margin-top:0cm;margin-bottom:15.0pt;line-height:107%;background:white;'><span style='font-size:15px;font-family:"Calibri",sans-serif;color:black;'>No use of Technological University of the Philippines Manila - College of Science &apos;s logo or other artwork will be allowed for linking absent a trademark license agreement.</span></p>
                            <h3 style='margin-top:0cm;margin-right:0cm;margin-bottom:13.5pt;margin-left:0cm;line-height:107%;font-size:16px;font-family:"Calibri Light",sans-serif;color:#1F3763;font-weight:normal;background:white;'><strong><span style='font-size:15px;line-height:107%;font-family:"Calibri",sans-serif;color:black;'>iFrames</span></strong></h3>
                            <p style='margin-right:0cm;margin-left:0cm;font-size:15px;font-family:"Calibri",sans-serif;margin-top:0cm;margin-bottom:15.0pt;line-height:107%;background:white;'><span style='font-size:15px;font-family:"Calibri",sans-serif;color:black;'>Without prior approval and written permission, you may not create frames around our Webpages that alter in any way the visual presentation or appearance of our Website.</span></p>
                            <h3 style='margin-top:0cm;margin-right:0cm;margin-bottom:13.5pt;margin-left:0cm;line-height:107%;font-size:16px;font-family:"Calibri Light",sans-serif;color:#1F3763;font-weight:normal;background:white;'><strong><span style='font-size:15px;line-height:107%;font-family:"Calibri",sans-serif;color:black;'>Content Liability</span></strong></h3>
                            <p style='margin-right:0cm;margin-left:0cm;font-size:15px;font-family:"Calibri",sans-serif;margin-top:0cm;margin-bottom:15.0pt;line-height:107%;background:white;'><span style='font-size:15px;font-family:"Calibri",sans-serif;color:black;'>We shall not be hold responsible for any content that appears on your Website. You agree to protect and defend us against all claims that is rising on your Website. No link(s) should appear on any Website that may be interpreted as libelous, obscene or criminal, or which infringes, otherwise violates, or advocates the infringement or other violation of, any third party rights.</span></p>
                            <h3 style='margin-top:0cm;margin-right:0cm;margin-bottom:13.5pt;margin-left:0cm;line-height:107%;font-size:16px;font-family:"Calibri Light",sans-serif;color:#1F3763;font-weight:normal;background:white;'><strong><span style='font-size:15px;line-height:107%;font-family:"Calibri",sans-serif;color:black;'>Your Privacy</span></strong></h3>
                            <p style='margin-right:0cm;margin-left:0cm;font-size:15px;font-family:"Calibri",sans-serif;margin-top:0cm;margin-bottom:15.0pt;line-height:107%;background:white;'><span style='font-size:15px;font-family:"Calibri",sans-serif;color:black;'>Please read Privacy Policy</span></p>
                            <h3 style='margin-top:0cm;margin-right:0cm;margin-bottom:13.5pt;margin-left:0cm;line-height:107%;font-size:16px;font-family:"Calibri Light",sans-serif;color:#1F3763;font-weight:normal;background:white;'><strong><span style='font-size:15px;line-height:107%;font-family:"Calibri",sans-serif;color:black;'>Reservation of Rights</span></strong></h3>
                            <p style='margin-right:0cm;margin-left:0cm;font-size:15px;font-family:"Calibri",sans-serif;margin-top:0cm;margin-bottom:15.0pt;line-height:107%;background:white;'><span style='font-size:15px;font-family:"Calibri",sans-serif;color:black;'>We reserve the right to request that you remove all links or any particular link to our Website. You approve to immediately remove all links to our Website upon request. We also reserve the right to amen these terms and conditions and it&rsquo;s linking policy at any time. By continuously linking to our Website, you agree to be bound to and follow these linking terms and conditions.</span></p>
                            <h3 style='margin-top:0cm;margin-right:0cm;margin-bottom:13.5pt;margin-left:0cm;line-height:107%;font-size:16px;font-family:"Calibri Light",sans-serif;color:#1F3763;font-weight:normal;background:white;'><strong><span style='font-size:15px;line-height:107%;font-family:"Calibri",sans-serif;color:black;'>Removal of links from our website</span></strong></h3>
                            <p style='margin-right:0cm;margin-left:0cm;font-size:15px;font-family:"Calibri",sans-serif;margin-top:0cm;margin-bottom:15.0pt;line-height:107%;background:white;'><span style='font-size:15px;font-family:"Calibri",sans-serif;color:black;'>If you find any link on our Website that is offensive for any reason, you are free to contact and inform us any moment. We will consider requests to remove links but we are not obligated to or so or to respond to you directly.</span></p>
                            <p style='margin-right:0cm;margin-left:0cm;font-size:15px;font-family:"Calibri",sans-serif;margin-top:0cm;margin-bottom:15.0pt;line-height:107%;background:white;'><span style='font-size:15px;font-family:"Calibri",sans-serif;color:black;'>We do not ensure that the information on this website is correct, we do not warrant its completeness or accuracy; nor do we promise to ensure that the website remains available or that the material on the website is kept up to date.</span></p>
                            <h3 style='margin-top:0cm;margin-right:0cm;margin-bottom:13.5pt;margin-left:0cm;line-height:107%;font-size:16px;font-family:"Calibri Light",sans-serif;color:#1F3763;font-weight:normal;background:white;'><strong><span style='font-size:15px;line-height:107%;font-family:"Calibri",sans-serif;color:black;'>Disclaimer</span></strong></h3>
                            <p style='margin-right:0cm;margin-left:0cm;font-size:15px;font-family:"Calibri",sans-serif;margin-top:0cm;margin-bottom:15.0pt;line-height:107%;background:white;'><span style='font-size:15px;font-family:"Calibri",sans-serif;color:black;'>To the maximum extent permitted by applicable law, we exclude all representations, warranties and conditions relating to our website and the use of this website. Nothing in this disclaimer will:</span></p>
                            <ul style="margin-bottom:0cm;" type="disc">
                                <li style='margin-top:0cm;margin-right:0cm;margin-bottom:8.0pt;margin-left:0cm;line-height:normal;font-size:15px;font-family:"Calibri",sans-serif;background:white;'><span style="color:black;">limit or exclude our or your liability for death or personal injury;</span></li>
                                <li style='margin-top:0cm;margin-right:0cm;margin-bottom:8.0pt;margin-left:0cm;line-height:normal;font-size:15px;font-family:"Calibri",sans-serif;background:white;'><span style="color:black;">limit or exclude our or your liability for fraud or fraudulent misrepresentation;</span></li>
                                <li style='margin-top:0cm;margin-right:0cm;margin-bottom:8.0pt;margin-left:0cm;line-height:normal;font-size:15px;font-family:"Calibri",sans-serif;background:white;'><span style="color:black;">limit any of our or your liabilities in any way that is not permitted under applicable law; or</span></li>
                                <li style='margin-top:0cm;margin-right:0cm;margin-bottom:8.0pt;margin-left:0cm;line-height:normal;font-size:15px;font-family:"Calibri",sans-serif;background:white;'><span style="color:black;">exclude any of our or your liabilities that may not be excluded under applicable law.</span></li>
                            </ul>
                            <p style='margin-right:0cm;margin-left:0cm;font-size:15px;font-family:"Calibri",sans-serif;margin-top:0cm;margin-bottom:15.0pt;line-height:107%;background:white;'><span style='font-size:15px;font-family:"Calibri",sans-serif;color:black;'>The limitations and prohibitions of liability set in this Section and elsewhere in this disclaimer: (a) are subject to the preceding paragraph; and (b) govern all liabilities arising under the disclaimer, including liabilities arising in contract, in tort and for breach of statutory duty.</span></p>
                            <p style='margin-right:0cm;margin-left:0cm;font-size:15px;font-family:"Calibri",sans-serif;margin-top:0cm;margin-bottom:15.0pt;line-height:107%;background:white;'><span style='font-size:15px;font-family:"Calibri",sans-serif;color:black;'>As long as the website and the information and services on the website are provided free of charge, we will not be liable for any loss or damage of any nature.</span></p>
                            <p style='margin-right:0cm;margin-left:0cm;font-size:15px;font-family:"Calibri",sans-serif;margin-top:0cm;margin-bottom:8.0pt;line-height:107%;'>&nbsp;</p>
</div>
</div>

@endsection

@section('privacy')
    <div class="card-body justify-content">
        <div style="text-align: justify; color: black; padding:1.25rem;" >
            <p style='margin-top:0cm;margin-right:0cm;margin-bottom:13.5pt;margin-left:0cm;line-height:normal;font-size:15px;font-family:"Calibri",sans-serif;background:white;'><strong><span style="color:black;">Privacy Policy of College of Science Knowledge Management System</span></strong></p>
            <p style='margin-top:0cm;margin-right:0cm;margin-bottom:15.0pt;margin-left:0cm;line-height:normal;font-size:15px;font-family:"Calibri",sans-serif;background:white;'><span style="color:black;">College of Science Knowledge Management System operates the www.coskms.edu website, which provides the SERVICE.</span></p>
            <p style='margin-top:0cm;margin-right:0cm;margin-bottom:15.0pt;margin-left:0cm;line-height:normal;font-size:15px;font-family:"Calibri",sans-serif;background:white;'><span style="color:black;">This page is used to inform website visitors regarding our policies with the collection, use, and disclosure of Personal Information if anyone decided to use our Service, the COS KMS website.</span></p>
            <p style='margin-top:0cm;margin-right:0cm;margin-bottom:15.0pt;margin-left:0cm;line-height:normal;font-size:15px;font-family:"Calibri",sans-serif;background:white;'><span style="color:black;">If you choose to use our Service, then you agree to the collection and use of information in relation with this policy. The Personal Information that we collect are used for providing and improving the Service. We will not use or share your information with anyone except as described in this Privacy Policy. Our Privacy Policy was created with the help of the&nbsp;</span><span style="color:black;"><a href="https://www.termsfeed.com/privacy-policy-generator/"><span style="color:black;text-decoration:none;">Privacy Policy Generator</span></a></span><span style="color:black;">.</span></p>
            <p style='margin-top:0cm;margin-right:0cm;margin-bottom:15.0pt;margin-left:0cm;line-height:normal;font-size:15px;font-family:"Calibri",sans-serif;background:white;'><span style="color:black;">The terms used in this Privacy Policy have the same meanings as in our Terms and Conditions, which is accessible at www.coskms.edu, unless otherwise defined in this Privacy Policy.</span></p>
            <p style='margin-top:0cm;margin-right:0cm;margin-bottom:13.5pt;margin-left:0cm;line-height:normal;font-size:15px;font-family:"Calibri",sans-serif;background:white;'><span style="color:black;">Information Collection and Use</span></p>
            <p style='margin-top:0cm;margin-right:0cm;margin-bottom:15.0pt;margin-left:0cm;line-height:normal;font-size:15px;font-family:"Calibri",sans-serif;background:white;'><span style="color:black;">For a better experience while using our Service, we may require you to provide us with certain personally identifiable information, including but not limited to your name, phone number, and postal address. The information that we collect will be used to contact or identify you.</span></p>
            <p style='margin-top:0cm;margin-right:0cm;margin-bottom:13.5pt;margin-left:0cm;line-height:normal;font-size:15px;font-family:"Calibri",sans-serif;background:white;'><span style="color:black;">Log Data</span></p>
            <p style='margin-top:0cm;margin-right:0cm;margin-bottom:15.0pt;margin-left:0cm;line-height:normal;font-size:15px;font-family:"Calibri",sans-serif;background:white;'><span style="color:black;">We want to inform you that whenever you visit our Service, we collect information that your browser sends to us that is called Log Data. This Log Data may include information such as your computer&rsquo;s Internet Protocol (&quot;IP&quot;) address, browser version, pages of our Service that you visit, the time and date of your visit, the time spent on those pages, and other statistics.</span></p>
            <p style='margin-top:0cm;margin-right:0cm;margin-bottom:13.5pt;margin-left:0cm;line-height:normal;font-size:15px;font-family:"Calibri",sans-serif;background:white;'><span style="color:black;">Cookies</span></p>
            <p style='margin-top:0cm;margin-right:0cm;margin-bottom:15.0pt;margin-left:0cm;line-height:normal;font-size:15px;font-family:"Calibri",sans-serif;background:white;'><span style="color:black;">Cookies are files with small amount of data that is commonly used an anonymous unique identifier. These are sent to your browser from the website that you visit and are stored on your computer&rsquo;s hard drive.</span></p>
            <p style='margin-top:0cm;margin-right:0cm;margin-bottom:15.0pt;margin-left:0cm;line-height:normal;font-size:15px;font-family:"Calibri",sans-serif;background:white;'><span style="color:black;">Our website uses these &quot;cookies&quot; to collection information and to improve our Service. You have the option to either accept or refuse these cookies, and know when a cookie is being sent to your computer. If you choose to refuse our cookies, you may not be able to use some portions of our Service.</span></p>
            <p style='margin-top:0cm;margin-right:0cm;margin-bottom:15.0pt;margin-left:0cm;line-height:normal;font-size:15px;font-family:"Calibri",sans-serif;background:white;'><span style="color:black;">For more general information on cookies, please read&nbsp;</span><span style="color:black;"><a href="https://www.termsfeed.com/blog/sample-cookies-policy-template/#What_Are_Cookies"><span style="color:black;text-decoration:none;">&quot;Cookies&quot; article from the TermsFeed website</span></a></span><span style="color:black;">.</span></p>
            <p style='margin-top:0cm;margin-right:0cm;margin-bottom:13.5pt;margin-left:0cm;line-height:normal;font-size:15px;font-family:"Calibri",sans-serif;background:white;'><span style="color:black;">Service Providers</span></p>
            <p style='margin-top:0cm;margin-right:0cm;margin-bottom:15.0pt;margin-left:0cm;line-height:normal;font-size:15px;font-family:"Calibri",sans-serif;background:white;'><span style="color:black;">We may employ third-party companies and individuals due to the following reasons:</span></p>
            <ul style="margin-bottom:0cm;" type="disc">
                <li style='margin-top:0cm;margin-right:0cm;margin-bottom:8.0pt;margin-left:0cm;line-height:normal;font-size:15px;font-family:"Calibri",sans-serif;background:white;'><span style="color:black;">To facilitate our Service;</span></li>
                <li style='margin-top:0cm;margin-right:0cm;margin-bottom:8.0pt;margin-left:0cm;line-height:normal;font-size:15px;font-family:"Calibri",sans-serif;background:white;'><span style="color:black;">To provide the Service on our behalf;</span></li>
                <li style='margin-top:0cm;margin-right:0cm;margin-bottom:8.0pt;margin-left:0cm;line-height:normal;font-size:15px;font-family:"Calibri",sans-serif;background:white;'><span style="color:black;">To perform Service-related services; or</span></li>
                <li style='margin-top:0cm;margin-right:0cm;margin-bottom:8.0pt;margin-left:0cm;line-height:normal;font-size:15px;font-family:"Calibri",sans-serif;background:white;'><span style="color:black;">To assist us in analyzing how our Service is used.</span></li>
            </ul>
            <p style='margin-top:0cm;margin-right:0cm;margin-bottom:15.0pt;margin-left:0cm;line-height:normal;font-size:15px;font-family:"Calibri",sans-serif;background:white;'><span style="color:black;">We want to inform our Service users that these third parties have access to your Personal Information. The reason is to perform the tasks assigned to them on our behalf. However, they are obligated not to disclose or use the information for any other purpose.</span></p>
            <p style='margin-top:0cm;margin-right:0cm;margin-bottom:13.5pt;margin-left:0cm;line-height:normal;font-size:15px;font-family:"Calibri",sans-serif;background:white;'><span style="color:black;">Security</span></p>
            <p style='margin-top:0cm;margin-right:0cm;margin-bottom:15.0pt;margin-left:0cm;line-height:normal;font-size:15px;font-family:"Calibri",sans-serif;background:white;'><span style="color:black;">We value your trust in providing us your Personal Information, thus we are striving to use commercially acceptable means of protecting it. But remember that no method of transmission over the internet, or method of electronic storage is 100% secure and reliable, and we cannot guarantee its absolute security.</span></p>
            <p style='margin-top:0cm;margin-right:0cm;margin-bottom:13.5pt;margin-left:0cm;line-height:normal;font-size:15px;font-family:"Calibri",sans-serif;background:white;'><span style="color:black;">Links to Other Sites</span></p>
            <p style='margin-top:0cm;margin-right:0cm;margin-bottom:15.0pt;margin-left:0cm;line-height:normal;font-size:15px;font-family:"Calibri",sans-serif;background:white;'><span style="color:black;">Our Service may contain links to other sites. If you click on a third-party link, you will be directed to that site. Note that these external sites are not operated by us. Therefore, we strongly advise you to review the Privacy Policy of these websites. We have no control over, and assume no responsibility for the content, privacy policies, or practices of any third-party sites or services.</span></p>
            <p style='margin-top:0cm;margin-right:0cm;margin-bottom:15.0pt;margin-left:0cm;line-height:normal;font-size:15px;font-family:"Calibri",sans-serif;background:white;'><span style="color:black;">Children&apos;s Privacy</span></p>
            <p style='margin-top:0cm;margin-right:0cm;margin-bottom:15.0pt;margin-left:0cm;line-height:normal;font-size:15px;font-family:"Calibri",sans-serif;background:white;'><span style="color:black;">Our Services do not address anyone under the age of 13. We do not knowingly collect personal identifiable information from children under 13. In the case we discover that a child under 13 has provided us with personal information, we immediately delete this from our servers. If you are a parent or guardian and you are aware that your child has provided us with personal information, please contact us so that we will be able to do necessary actions.</span></p>
            <p style='margin-top:0cm;margin-right:0cm;margin-bottom:13.5pt;margin-left:0cm;line-height:normal;font-size:15px;font-family:"Calibri",sans-serif;background:white;'><span style="color:black;">Changes to This Privacy Policy</span></p>
            <p style='margin-top:0cm;margin-right:0cm;margin-bottom:15.0pt;margin-left:0cm;line-height:normal;font-size:15px;font-family:"Calibri",sans-serif;background:white;'><span style="color:black;">We may update our Privacy Policy from time to time. Thus, we advise you to review this page periodically for any changes. We will notify you of any changes by posting the new Privacy Policy on this page. These changes are effective immediately, after they are posted on this page.</span></p>
            <p style='margin-top:0cm;margin-right:0cm;margin-bottom:13.5pt;margin-left:0cm;line-height:normal;font-size:15px;font-family:"Calibri",sans-serif;background:white;'><span style="color:black;">Contact Us</span></p>
            <p style='margin-top:0cm;margin-right:0cm;margin-bottom:15.0pt;margin-left:0cm;line-height:normal;font-size:15px;font-family:"Calibri",sans-serif;background:white;'><span style="color:black;">If you have any questions or suggestions about our Privacy Policy, do not hesitate to contact us.</span></p>
        </div>
    </div>

@endsection
